# Made by Ezer for my projects with love <3

# Какое сообщение высветиться при вводе запрещённых команд.
# Форматирование с помощью знака "&"!
messages:
  # Команда reload
  # Право: eblocker.command.reload
  reload: "&7(&cEBlocker&7) >> &bReload successfully!"
  alertmsg: "&7(&cEBlocker&7) >> &cКоманда заблокирована!"
  # permission: "&7(&cEBlocker&7) >> &cУ вас недостаточно прав!"
  # nullargs: "&7(&cEBlocker&7) >> &cИспользуйте /eblocker reload"

# Команды которые будут заблокированы
cmds:
  - 'pl'
  - 'bukkit:pl'
  - 'about'
  - 'd 1.'
  - 'd 2.'
  - 'd 3.'
  - 'd 4.'
  - 'd 15.'
  - 'd 16.'
  - 'd 17.'
  - 'd 18.'
  - 'd 19.'
  - 'D 1.'
  - 'D 2.'
  - 'D 3.'
  - 'D 4.'
  - 'D 5.'
  - 'D 6.'
  - 'D 7.'
  - 'D 8.'
  - 'D 9.'
  - 'D .1'
  - 'D .2'
  - 'D .3'
  - 'D .4'
  - 'D .5'
  - 'D .6'
  - 'D .7'
  - 'D .8'
  - 'D .9'
  - 'D .'
  - 'D .10'
  - 'D .11'
  - 'D .12'
  - 'D .13'
  - 'D .14'
  - 'D .15'
  - 'D .16'
  - 'D .17'
  - 'D .18'
  - 'D .19'
  - 'D 10.'
  - 'D 11.'
  - 'D 12.'
  - 'D 13.'
  - 'D 14.'
  - 'D 15.'
  - 'D 16.'
  - 'D 17.'
  - 'D 18.'
  - 'D 19.'