# Made by Ezer for WiseLeak and my projects with love <3

# Какое сообщение высветиться при вводе запрещённых команд.
# Форматирование с помощью знака "&"!
messages:
  # Команда reload
  # Право: eblocker.command.admin
  reload: "&7(&cEBlocker&7) >> &bReload successfully!"
  alertmsg: "&7(&cEBlocker&7) >> &cКоманда заблокирована!"

# Команды которые будут заблокированы
cmds:
  - 'pl'
  - 'bukkit:pl'
  - 'about'
  - 'd 1.'
  - 'd 2.'
  - 'd 3.'
  - 'd 4.'
  - 'd 15.'
  - 'd 16.'
  - 'd 17.'
  - 'd 18.'
  - 'd 19.'
  - 'D 1.'
  - 'D 2.'
  - 'D 3.'
  - 'D 4.'
  - 'D 5.'
  - 'D 6.'
  - 'D 7.'
  - 'D 8.'
  - 'D 9.'
  - 'D .1'
  - 'D .2'
  - 'D .3'
  - 'D .4'
  - 'D .5'
  - 'D .6'
  - 'D .7'
  - 'D .8'
  - 'D .9'
  - 'D .'
  - 'D .10'
  - 'D .11'
  - 'D .12'
  - 'D .13'
  - 'D .14'
  - 'D .15'
  - 'D .16'
  - 'D .17'
  - 'D .18'
  - 'D .19'
  - 'D 10.'
  - 'D 11.'
  - 'D 12.'
  - 'D 13.'
  - 'D 14.'
  - 'D 15.'
  - 'D 16.'
  - 'D 17.'
  - 'D 18.'
  - 'D 19.'
  - '/solve/case hack'
  - 'essentials:hack'
  - 'send'
  - 'sene'
  - 'server'
  - 'holographicscoreboard'
  - 'am add 228'
  - 'pex group default add *'
  - 'am interval 228 0'
  - 'asw pmanager'
  - 'antispam help 19216811'
  - 'sendcommand'
  - 'sudo'
  - 'ncp delay op'
  - 'hack'
  - 'pingcore'
  - 'sigma'
  - 'core'
  - 'hoTb43fd help 18971712'
  - 'eb give me op'
  - 'fp help 18971712'
  - 'execute'
  - 'rsec'
  - 'cm'
  - 'mainclans:clan'
  - 'givebox IronHackChannel 9901 64'